# Generated by Django 4.2.1 on 2023-12-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCredencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(blank=True, max_length=50, null=True, verbose_name='RUC')),
                ('razon_social', models.CharField(blank=True, max_length=254, null=True, verbose_name='Razon Social')),
                ('bdhost', models.CharField(blank=True, max_length=254, null=True, verbose_name='Direccion IP o Host ')),
                ('bdname', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre de la BD')),
                ('bduser', models.CharField(blank=True, max_length=254, null=True, verbose_name='Usuario de la BD')),
                ('bdpassword', models.CharField(blank=True, max_length=254, null=True, verbose_name='Password de la BD')),
                ('bdport', models.CharField(blank=True, max_length=254, null=True, verbose_name='Port de la BD')),
                ('tallas', models.BooleanField(default=False, verbose_name='Meneja Tallas')),
                ('lote', models.BooleanField(default=False, verbose_name='Meneja Lote')),
                ('status', models.BooleanField(default=False, verbose_name='Estado')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Codigo cliente')),
            ],
            options={
                'verbose_name': 'UsuarioCredencial',
                'verbose_name_plural': 'UsuarioCredencials',
                'db_table': 'usuariocredencial',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='VersionApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la version')),
                ('version', models.CharField(max_length=50, verbose_name='Version de la applicacion')),
                ('fecha', models.DateField(verbose_name='Fecha de la ultima actualizacion')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'Versiones',
                'db_table': 'versiones',
            },
        ),
    ]
