# Generated by Django 4.2.1 on 2023-05-09 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCredencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=50, verbose_name='RUC')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario nombre')),
                ('password', models.CharField(max_length=254, verbose_name='Password')),
                ('bdhost', models.CharField(blank=True, max_length=254, null=True, verbose_name='Direecion IP o Host ')),
                ('bdname', models.CharField(blank=True, max_length=254, null=True, verbose_name='Nombre de la BD')),
                ('bduser', models.CharField(blank=True, max_length=254, null=True, verbose_name='Usuario de la BD')),
                ('bdpassword', models.CharField(blank=True, max_length=254, null=True, verbose_name='Password de la BD')),
                ('bdport', models.CharField(blank=True, max_length=254, null=True, verbose_name='Port de la BD')),
                ('empresa_ruc', models.CharField(max_length=22, verbose_name='Empresa RUC')),
                ('empresa_razon_social', models.CharField(max_length=255, verbose_name='Empresa razon social')),
            ],
            options={
                'verbose_name': 'UsuarioCredencial',
                'verbose_name_plural': 'UsuarioCredencials',
                'db_table': 'usuariocredencial',
                'ordering': ['id'],
            },
        ),
    ]
