# Generated by Django 4.2.1 on 2023-05-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocredencial',
            name='empresa_razon_social',
        ),
        migrations.RemoveField(
            model_name='usuariocredencial',
            name='empresa_ruc',
        ),
        migrations.AddField(
            model_name='usuariocredencial',
            name='razon_social',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Razon Social'),
        ),
        migrations.AlterField(
            model_name='usuariocredencial',
            name='password',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='usuariocredencial',
            name='ruc',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RUC'),
        ),
        migrations.AlterField(
            model_name='usuariocredencial',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Usuario nombre'),
        ),
    ]
