# Generated by Django 4.2.1 on 2023-12-20 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0002_configcliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcliente',
            name='cliente_user',
            field=models.BooleanField(default=False, verbose_name='Cliente asigando por usuario'),
        ),
    ]
