# Generated by Django 5.0.1 on 2024-02-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0003_configcliente_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcliente',
            name='guid_lote',
            field=models.BooleanField(default=False, verbose_name='El campo Lote es string'),
        ),
        migrations.AlterField(
            model_name='configcliente',
            name='cliente_user',
            field=models.BooleanField(default=False, verbose_name='Cliente asignado por usuario'),
        ),
    ]
