# Generated by Django 4.2.1 on 2023-06-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0003_usuariocredencial_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocredencial',
            name='password',
        ),
        migrations.RemoveField(
            model_name='usuariocredencial',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='usuariocredencial',
            name='bdhost',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Direccion IP o Host '),
        ),
    ]
