# Generated by Django 4.2.1 on 2023-07-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0004_remove_usuariocredencial_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocredencial',
            name='tallas',
            field=models.BooleanField(default=False, verbose_name='Meneja Tallas'),
        ),
    ]
