# Generated by Django 4.2.1 on 2023-07-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0005_usuariocredencial_tallas'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocredencial',
            name='lote',
            field=models.BooleanField(default=False, verbose_name='Meneja Lote'),
        ),
    ]
