# Generated by Django 4.2 on 2024-09-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0007_rename_fpk_file_versionapp_apk_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configcliente',
            options={'verbose_name': 'Configuracion del Cliente', 'verbose_name_plural': 'Configuracion de Clientes'},
        ),
        migrations.AddField(
            model_name='configcliente',
            name='valida_stock',
            field=models.BooleanField(default=True, verbose_name='Valida stock'),
        ),
    ]
