# Generated by Django 5.0.1 on 2024-09-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0007_rename_fpk_file_versionapp_apk_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcliente',
            name='valida_stock',
            field=models.BooleanField(default=True, verbose_name='Valida stock'),
        ),
    ]
