# Generated by Django 4.2.1 on 2023-11-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apirest', '0010_versionapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocredencial',
            name='codigo',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Codigo cliente'),
        ),
    ]
